image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - test
  - docker

cargo_build:
  image: rustlang/rust:nightly
  stage: build
  script:
    - cd indi02
    - cargo build --verbose

cargo_test:
  image: rustlang/rust:nightly
  stage: test
  script:
    - cd indi02
    - cargo test --verbose

docker_build:
  stage: docker
  script:
    - docker build . -t myapp
    - cat $DOCKERHUB_PASSWORD_FILE | docker login -u $DOCKERHUB_USERNAME --password-stdin
    - docker tag myapp $DOCKERHUB_USERNAME/myapp
    - docker push $DOCKERHUB_USERNAME/myapp